// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHDco_pOOZsiUSoSXvIZve0iBAk9cZrsc',
    appId: '1:272234770586:web:4bb34b0b967cbd3c452f23',
    messagingSenderId: '272234770586',
    projectId: 'petcarelogin',
    authDomain: 'petcarelogin.firebaseapp.com',
    storageBucket: 'petcarelogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbA_ZV4iZ-1qr1JEgb3D7UF9LUhBkauWI',
    appId: '1:272234770586:android:50e32ad543c2c93c452f23',
    messagingSenderId: '272234770586',
    projectId: 'petcarelogin',
    storageBucket: 'petcarelogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9erZL37X54plvCL5jRZOzuMDFWbyA31c',
    appId: '1:272234770586:ios:1fffffd33825cc2a452f23',
    messagingSenderId: '272234770586',
    projectId: 'petcarelogin',
    storageBucket: 'petcarelogin.appspot.com',
    iosClientId: '272234770586-nkgua60k63krsgqevpdsri20224lvh8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9erZL37X54plvCL5jRZOzuMDFWbyA31c',
    appId: '1:272234770586:ios:1fffffd33825cc2a452f23',
    messagingSenderId: '272234770586',
    projectId: 'petcarelogin',
    storageBucket: 'petcarelogin.appspot.com',
    iosClientId: '272234770586-nkgua60k63krsgqevpdsri20224lvh8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );
}
